language: python
python:
- '3.6'
- 3.7-dev
script: python setup.py test
deploy:
  provider: pypi
  user: felipaoo
  on:
    tags: true
  password:
    secure: PF7LbmXW0fcGLZWJhk7KcpG4U+z58exlU27hd4d5iDtQH70ZOrrc+RYlEeAt0gz7jv6jTz+z2aucT/gcOgcyF50sJEUNZiX6GfQxiLqCC1segrHK7FpAIsgSfvETYRfXeKdRBKUYP1Zs3ioxu7NB3a5fH4GS/ZKKNx1wOaIAHXgKsYwkESmZOTl8xxkc1GJpZWMpdbPBEkH2rGWUwR0rcbtnKFabJdJT0OfX08I6bQAAXGuRl1/pozCqbq5WyMSifsbjdIrTDsofN2uQktvvG6rBqoMk0m1h/RceZCqnvchVi0Q9+Tv82C+4RPoJUiTtUA4y51SwShar1rkGsmUk4xjI7PQWfw3d/vT395CFMkwpyxYH7tDMjOsOXUBaT6TatZGRLm/Vo5yBNk5/W3umc2GmrgvwT8h+QmWbvoc1TlJrOCRYRjijgKk3jfCH+8lN0P3p5HIXUhZhcbLvyIFrnkge5LZwOMjnHFlM1iT6dv1zNqU377/d4vEjibsT+TtfIYhHe30m1hhVDddPcIjUD3x2/yN863mIcZpRHP0pTzuIWVk8COfTO/2HEv5uPP9FUI/04j19hrR2Art83XYGkvduIjRRwUWxb2hUVtRsiQ5VEZyP+fRukqXbJD1/tIfZpyWD8Y2vr2+x6WvxCNNnV7nNDKQ18dXRmGXKeEacOL4=
