language: python
python:
- '3.6'
- '3.7-dev'
script: python setup.py test

jobs:
  include:
    - stage: pypi release
      python: '3.7-dev'
      script: echo "release package to pypi"
      deploy:
        provider: pypi
        user: felipaoo
        on:
          tags: true
        password:
          secure: "mwqUOlFwm2ae8lrTxxoGue8o9EyM8qSrjPJkruxp7OAn2EthO3//s9UdxSeAleaDYXxfx1d8VvLAg9beUM6phl/6IDrVbmiEPCn3/EjjyPyCUmXmL4gfxrg4N0wr5yoDUC5/6iQ0g0aJmDaDRLzT2m6I82rqOac20pTjEOczSfmXZWXpUt3MslbqeZ+dxXLwMMXIzs/R6qlCJFsP/g76PynTPT4S52Tv0YJ2csoqPMLQqoMgMeIW/7vGSTdmZrvwseVQGuzExfvAQLDXdHLoWn162cO5oBa7uLXbkxFWsBA3mJtzSGKnBRjN/wFpTdOe6DOHOd108BPvjnzn4ydsuNLDaCJ+Up+jyhomLlSdHBZuz+sEyxSJFzDAgCr5IewClsEhpCBOzi5DkRZla+loo+/8sXbQKb5RtzCQksTtLcDNqE5MkFwajuS53EpVF32ER9WhRN6GYc8BZoidwYeuy/Uxbb9ZxN2f+PyfAvOWlur84Ki2X1Lca5pvnh8u7WCASw2W89BsDGDOJ7GYgWKmDy0DR7LOhBpcUNAFQSryYCMDedoq9AXRYmW5lb/95q/V97vE1vwjJ8hU/4O1oAJSoNErqKBgQjkE603US61kFIe55i8sUsOIquAvuJk+jUk1uykXc3A4A2NEjuqvuiJU6SUYHxXQmpGdOJkYNUiqZaU="
        server: https://test.pypi.org/legacy/
        distributions: sdist bdist_wheel
