language: python
python:
- '3.6'
- '3.7-dev'
script: python setup.py test

jobs:
  include:
    - stage: pypi release
      python: 3.7-dev
      script: echo "release package to pypi"
      deploy:
        provider: pypi
        user: felipaoo
        on:
          tags: true
        password:
          secure: Cwitto6cOKsmpRdkU2Uz5kq2BRB/W1GFzWgXg7Fhm6EgcSs7dpT2Xt1eseP9Jfx/GHxRaJusY2Jmp1Cmiib5zR09y5mcdaT9Y4Nz+5+PyWv1+v97NurRH0Lw2B38T0MpBIktHkPbP6ugYu+PSzMfpnff4PoRPyrRShGThLNj/PHzTSPbPhjdB+yG4T2Vmj4vfkKO40YWgKnfDYh7jJ0aBpHbFNDXqtIZnx27xF7SpyHNJva+kvC2mUWFEL+MFvpxaQ71k4IU157TH3zHMYegRBiwDosry9M+TCYGE+YMex/oxl/3fV2SjXo99oQi1zEsPQ+6of4Zlfph9svyVgAAx0nnFordOLjjzsEMngrHntCeKY+FiRudLfpioqIFswgJecW14dT8NBuRiIM+f3p6STU9uRPfuGwPG1/VwKmLi40FRTY5I8OuU9QAOA73xYpmDmNJf9BKcW07TFViJHl4NvQ/81LL13Hs7wNbyb/w9AQ7o7EDEvngBFyUFVTGemFGJTxOifcwf0VnIJlzPqKK0H5gBWHmWKGnnQODK2cjb34u/8uIdgKgu72zCz6u+6MWGR6rL6VpOY/oJRxvcmqKT2MKOOHmGmL/GrIW8SjGVdF5DoCVzhfilRxoQngbK2C8WL5zBLXLJYrJLTvjYQ9MoNCw9I2U5b3RxlRWYOA7DMU=
        server: https://test.pypi.org/legacy/
        distributions: sdist bdist_wheel
