language: python
python:
- '3.6'
- 3.7-dev
script: python setup.py test
deploy:
  provider: pypi
  user: felipaoo
  on:
    tags: true
  password:
    secure: "wq2VXGpTg27L59YHEVvt4WLPkyiRd8RHTItUiUiEMjFS//P4NHH9GpAoxpcMvZynKArWAKcbgMwMALu5SKSBMCoDl/oLVGUOR08Rfq7ZPynTHyEoet8BE49oerJD2OJhxSCNgftLYvL6a5PJxzPv8c2/dswWjIWx/MUQmhScPbGR83bQi3JB+0eRERERJfBfsZD6SDAk+RIhQ52cUWGo7GjdAv372HVQp5rONGv9XKILjgXB0mVekcTQD1IyBStMMUmZnt1m5apDIMSpcaAql6+OCVpPIFOR9do/UeUTbONAhdrY7XnrxhLx7a21oOakbBTp2KcyyUXjvdWY7AlQl83dA2nQZlVrf3z3kb3nmcRmSLY6yxvHFpf/C3BEPDKIpXjb6fweMFH8hTlw1AoOzhuf7gNvOmjuql4VZ1kje5M+/gutL6R+lPuk/N8B11CKRN6ppyctAIo7SjQzS6StpDcQg/ZjUW7mv5aU1I2gkvVuIwsK7J2gK7kRBLfxS56tSosJ+e58zffHoGpo2ewJ5PN6qYTGhU09ITL2Jqw+EooledzVRpDaX38xFqxcBZO7ScFUSgiYfpNBp8++SOxzpyC37BYjA1sfQ0FP++GLF79CAAAUCVvCiImZ4kDYYmfSzYkX883LmJ2sAHAmh5YdcbvIhjYvg8igu7zshyAigK4="
